Tracker:AddLocations("locations/Barrel Cannon Canyon.json")
Tracker:AddLocations("locations/Blackout Basement.json")
Tracker:AddLocations("locations/Boss Dumb Drum.json")
Tracker:AddLocations("locations/Bouncy Bonanza.json")
Tracker:AddLocations("locations/Bumble B Rumble.json")
Tracker:AddLocations("locations/Clam City.json")
Tracker:AddLocations("locations/Coral Capers.json")
Tracker:AddLocations("locations/Croctopus Chase.json")
Tracker:AddLocations("locations/Defeated Dumb Drum.json")
Tracker:AddLocations("locations/Defeated Master Necky.json")
Tracker:AddLocations("locations/Defeated Master Necky Snr..json")
Tracker:AddLocations("locations/Defeated Queen B..json")
Tracker:AddLocations("locations/Defeated Really Gnawty.json")
Tracker:AddLocations("locations/Defeated Very Gnawty.json")
Tracker:AddLocations("locations/Elevator Antics.json")
Tracker:AddLocations("locations/Forest Frenzy.json")
Tracker:AddLocations("locations/Ice Age Alley.json")
Tracker:AddLocations("locations/Jungle Hijinx.json")
Tracker:AddLocations("locations/Jungle Hijinxs.json")
Tracker:AddLocations("locations/Loopy Lights.json")
Tracker:AddLocations("locations/Manic Mincers.json")
Tracker:AddLocations("locations/Millstone Mayhem.json")
Tracker:AddLocations("locations/Mine Cart Carnage.json")
Tracker:AddLocations("locations/Mine Cart Madness.json")
Tracker:AddLocations("locations/Misty Mine.json")
Tracker:AddLocations("locations/Necky's Nuts.json")
Tracker:AddLocations("locations/Necky's Revenge.json")
Tracker:AddLocations("locations/Oil Drum Alley.json")
Tracker:AddLocations("locations/Orang-utan Gang.json")
Tracker:AddLocations("locations/Platform Perils.json")
Tracker:AddLocations("locations/Poison Pond.json")
Tracker:AddLocations("locations/Really Gnawty Rampage.json")
Tracker:AddLocations("locations/Reptile Rumble.json")
Tracker:AddLocations("locations/Rope Bridge Rumble.json")
Tracker:AddLocations("locations/Ropey Rampage.json")
Tracker:AddLocations("locations/Slipslide Ride.json")
Tracker:AddLocations("locations/Snow Barrel Blast.json")
Tracker:AddLocations("locations/Stop & Go Station.json")
Tracker:AddLocations("locations/Tanked Up Trouble.json")
Tracker:AddLocations("locations/Temple Tempest.json")
Tracker:AddLocations("locations/Torchlight Trouble.json")
Tracker:AddLocations("locations/Tree Top Town.json")
Tracker:AddLocations("locations/Trick Track Trek.json")
Tracker:AddLocations("locations/Very Gnawty's Lair.json")
Tracker:AddLocations("locations/Vulture Culture.json")
Tracker:AddLocations("locations/Winky's Walkway.json")
Tracker:AddLocations("locations/World Map.json")
